
---
deployment:
  tasks:
    - export DEPLOYPATH=/home/njengas1/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp comingsoon.html $DEPLOYPATH
    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R head $DEPLOYPATH
