---
deployment:
  tasks:
    - export DEPLOYPATH=/home/njengas2/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp comingsoon.html $DEPLOYPATH

    - /bin/rm -rf $DEPLOYPATH/images
    - /bin/rm -rf $DEPLOYPATH/css
    - /bin/rm -rf $DEPLOYPATH/js
    - /bin/rm -rf $DEPLOYPATH/head
    - /bin/rm -rf $DEPLOYPATH/writing_dev
    - /bin/rm -rf $DEPLOYPATH/imageResizer

    - /bin/cp -R images $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R head $DEPLOYPATH
    - /bin/cp -R writing_dev $DEPLOYPATH
    - /bin/cp -R imageResizer $DEPLOYPATH
